### PR TITLE
CZI support of multiple sections

### PR DESCRIPTION
**Pull request by frauzufall**
This PR adds support for multiple sections in one CZI file. 
Example (list image series resolutions in CZI with marked sections):
```
15998 x 10894 // first section
7999 x 5447
3999 x 2723
1999 x 1361
999 x 680
20321 x 8758 // second section
10160 x 4379
5080 x 2189
2540 x 1094
1270 x 547
635 x 273
14569 x 10897 // third section
7284 x 5448
3642 x 2724
1821 x 1362
910 x 681
720 x 578 // label image
1580 x 748 // macro image
```

Steps:
- Open CZI file via Plugins > Segmentation > Labkit (CZI / experimental)
- Choose section (this is the new Dialog)
- Choose resolution of section (this will be replaced with resolution pyramid loading later)

According to the index of the section (starting with 1), the fitting labeling file will be loaded:
image data: `myfile.czi`
labeling file for section 1: `myfile-1.czi.labeling`
labeling file for section 2: `myfile-2.czi.labeling`

Currently the labeling is only scaled correctly if one opens the section in the highest resolution.

### CODE REVIEW

**Comment by frauzufall** [comment]
TODO check label resolution

**Comment by frauzufall** [comment]
related issue: https://github.com/maarzt/imglib2-labkit/issues/19

**Comment by imagejan** [comment]
Is there a possibility to avoid special-casing CZI files? There are multiple formats known to Bio-Formats that support both multi-series and multi-resolution files, and Bio-Formats provides API in ` IFormatReader` to read (meta-)data from specific series and resolutions.

It would be a shame if this remained limited to czi files in this plugin :)

**Comment by frauzufall** [comment]
Hey @imagejan , thank you for your answer and yes, it would be great to not be so specific at this point. We currently get CZI files from a lab which do not seem to contain information about multi-resolution, at least we have not found a way yet. `resolutonCount` is `1` and `resolution` is `0` for all series. Also no hint in the metadata. Therefore this is our solution for this specific situation. 
Ideally (and that should be the goal) we want to open multi-series and multi-resolution images from ImageJ, making this importer obsolete altogether.

**Comment by maarzt** [comment]
This branch has been cleaned up and merged already

**Pull request closed without merging**
