### PR TITLE
Improve screen resolution during drawing

### PR DESCRIPTION
**Pull request by maarzt**
Hi @tpietzsch, 

This is the old branch that I used when coding the interval painting with BDV.
I now see a design problem with it: The code has a Model-View-Controler pattern.
With:
 viewer = BDV
 model = ImageLabelingModel
 controller = LabelBrushController

When the brush is used, the LabelBrushController fires a ImageLabelingModel.dataChangeNotifier().notifyListeners() event. Which tells all the listeners that the content of ImageLabelingModel.labeling() changed. One of the listeneres if th BDV / BasicLabelingComponent, that repaints it screen. This PR adds a "screen interval" as parameter to the event. The controller and viewer can correctly interpret this "screen interval" as they know the current viewer transform. But the other listerners don't know
the current viewer transform. Hence the "screen interval" can not be interpreted correctly by them.

This is not a functional problem, just a little bit dirty about the design. Does any apparent solution come to your mind?

### CODE REVIEW

**Comment by tpietzsch** [comment]
> This is not a functional problem, just a little bit dirty about the design. Does any apparent solution come to your mind?

Nothing simple.
To make the changes viewer transform independent, it would make sense to give the updated region in source space:
which source, which timepoint, and which 3D interval change. BDV could then react to this, checking whether the current screen region is affected by the update, and re-painting the corresponding screen interval if it is.

Longer-term it would be good to push this type of change notification framework deeper into bigdataviewer or even imglib2. It could happen automatically when pixel data is modified through accesses, or manually triggered. Automatic could be on the access level, maybe a more powerful version of the `Dirty` accesses in imglib2. But it is relatively unclear to me how that would look exactly.

Anyway, for now, I think your solution is fine...

**Comment by tpietzsch** [comment]
I rebased it onto current master. From my point of view it's ready to merge...

**Comment by maarzt** [comment]
Ok, lets stay with the current solution then.

**Comment by maarzt** [comment]
I love how smooth the drawing works now!

But I found a bug too. I get an exception whenever the brush goes off the screen / bdv window. The exception can be reproduced like this:
```java
BdvStackSource< IntType > bdvSource = BdvFunctions.show( ArrayImgs.ints( 100, 100 ), "black" );
Thread.sleep( 1000 );

// Request to repaint an interval which is off screen -> causes exception
bdvSource.getBdvHandle().getViewerPanel().requestRepaint( Intervals.createMinSize(-50, -50, 10, 10) ); 
```

While debugging the code I found that these lines calculate an interval with negative height or width:
https://github.com/bigdataviewer/bigdataviewer-core/blob/master/src/main/java/bdv/viewer/render/ScreenScales.java#L234-L239
This later on causes the exception. There are of cause two ways to fix this:
1. Never request to repaint an interval which is off screen.
2. Change BDV core to properly handle an off screen repaint request.

It think the second option is more robust and better. @tpietzsch What do you think?

**Comment by tpietzsch** [comment]
Yes, second option sounds better. I'll fix it...

**Comment by tpietzsch** [comment]
@maarzt it's fixed now

**Comment by maarzt** [comment]
@tpietzsch Thank you for working on this!

**Pull request merged**
